go:
  # Whenever the Go version is updated here, .travis.yml and
  # .circle/config.yml should also be updated.
  version: 1.13
repository:
  path: github.com/fusakla/k8s-service-broadcasting
build:
  binaries:
    - name: k8s-service-broadcasting
      path: ./
  flags: -a -tags netgo
#  ldflags: |
#    -X github.com/fusakla/k8s-service-broadcasting/metrics.appVersion={{.Version}}
#    -X github.com/fusakla/k8s-service-broadcasting/metrics.gitRevision={{.Revision}}
#    -X github.com/fusakla/k8s-service-broadcasting/metrics.gitBranch={{.Branch}}
#    -X github.com/fusakla/k8s-service-broadcasting/metrics.gitTag={{.Version}}
tarball:
  files:
    - LICENSE
    - NOTICE
crossbuild:
  platforms:
    - linux/amd64
    - darwin/amd64
    - windows/amd64
