---
version: 2.1

executors:
  golang:
    docker:
    - image: circleci/golang:1.13

jobs:
  test:
    executor: golang
    steps:
      - checkout
      - run: make golangci-lint
      - run: make

  publish_docker:
    executor: golang
    steps:
      - checkout
      - setup_remote_docker
      - run: make docker-publish

workflows:
  version: 2
  k8s-service-broadcasting:
    jobs:
    - test:
        filters:
          tags:
            only: /.*/
    - publish_docker:
        requires:
        - test
        filters:
          tags:
            only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
          branches:
            only: master
