apiVersion: v1
kind: Service
metadata:
  name: prometheus-pushgateway
  labels:
    app: prometheus-pushgateway
spec:
  type: NodePort
  ports:
    - name: http
      port: 9091
      protocol: TCP
      nodePort: 30001
  selector:
    app: prometheus-pushgateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-pushgateway
spec:
  selector:
    matchLabels:
      app: prometheus-pushgateway
  replicas: 3
  template:
    metadata:
      labels:
        app: prometheus-pushgateway
    spec:
      containers:
        - name: prometheus-pushgateway
          image: prom/pushgateway:v1.0.1
          livenessProbe:
            httpGet:
              port: gateway
              path: /-/healthy
          ports:
            - name: gateway
              containerPort: 9091
          resources:
            requests:
              cpu: "50m"
              memory: "50Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
